CREATE TABLE users (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	name varchar(64) NOT NULL UNIQUE,
	email varchar(256) NOT NULL UNIQUE,
	active BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE otps (
	user_id UUID REFERENCES users(id) ON DELETE CASCADE,
	code VARCHAR(64) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
